"""added esp settings table

Revision ID: 5ca6f7023a79
Revises: 87a0e53332fe
Create Date: 2021-11-13 20:21:14.474853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca6f7023a79'
down_revision = '87a0e53332fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esp_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plots_id', sa.Integer(), nullable=True),
    sa.Column('manual_trigger', sa.Integer(), nullable=True),
    sa.Column('manual_amount', sa.Integer(), nullable=True),
    sa.Column('manual_trigger_2', sa.Integer(), nullable=True),
    sa.Column('manual_amount_2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('esp_settings')
    # ### end Alembic commands ###
