"""empty message

Revision ID: 6f487ead08e4
Revises: 
Create Date: 2021-10-26 20:17:06.106034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f487ead08e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=45), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plots_users_id'), 'plots', ['users_id'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('plots_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['plots_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_plots_id'), 'sensors', ['plots_id'], unique=False)
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sensors_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['sensors_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_data_sensors_id'), 'sensor_data', ['sensors_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_data_sensors_id'), table_name='sensor_data')
    op.drop_table('sensor_data')
    op.drop_index(op.f('ix_sensors_plots_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_plots_users_id'), table_name='plots')
    op.drop_table('plots')
    op.drop_table('users')
    # ### end Alembic commands ###
