"""API key for plots added

Revision ID: 87a0e53332fe
Revises: 848636aa4b59
Create Date: 2021-10-30 20:37:58.128157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a0e53332fe'
down_revision = '848636aa4b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plots', sa.Column('api_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plots', 'api_key')
    # ### end Alembic commands ###
