"""added latest water field

Revision ID: 8fca23cec6bb
Revises: ef52ecd57be3
Create Date: 2022-02-18 17:18:08.532743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fca23cec6bb'
down_revision = 'ef52ecd57be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plots', sa.Column('latest_water', sa.DateTime(),
                  nullable=True, server_default='2020-01-01 12:00:00.000000'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plots', 'latest_water')
    # ### end Alembic commands ###
