"""more esp settings and data timestamp

Revision ID: ef52ecd57be3
Revises: c3933b7cfad4
Create Date: 2021-11-27 17:06:06.378740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef52ecd57be3'
down_revision = 'c3933b7cfad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('esp_settings', sa.Column('update_interval', sa.Integer(), nullable=True))
    op.add_column('esp_settings', sa.Column('reserved_1', sa.Integer(), nullable=True))
    op.add_column('esp_settings', sa.Column('reserved_2', sa.Integer(), nullable=True))
    op.add_column('sensor_data', sa.Column('latest_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_data', 'latest_update')
    op.drop_column('esp_settings', 'reserved_2')
    op.drop_column('esp_settings', 'reserved_1')
    op.drop_column('esp_settings', 'update_interval')
    # ### end Alembic commands ###
